In [10]:
import pandas as pd

In [11]:
lfpl_loc = pd.read_csv('../data/Louisville_KY_Free_Public_Libraries-2.csv')

In [12]:
lfpl_loc.head()

,X,Y,OBJECTID,LFPL_NAME,LFPL_ADD,LFPL_LOC,LFPL_WEB,TELEPHONE,LATITUDE,LONGITUDE
0,1.236710e+06,263517.29000,1,BON AIR,2816 DEL RIO PL,LOUISVILLE KY 40220,https://www.lfpl.org/bon-air-library,502-574-1795,38.215179,-85.655178
1,1.205783e+06,224288.89875,2,FAIRDALE,10620 WEST MANSLICK RD,FAIRDALE KY 40118,https://www.lfpl.org/fairdale-1,502-375-2051,38.106126,-85.760568
2,1.203085e+06,252215.11875,3,IROQUOIS,601 WEST WOODLAWN AVE,LOUISVILLE KY 40215,https://www.lfpl.org/iroquois-library,502-574-1720,38.182680,-85.771544
3,1.226610e+06,278010.77000,4,CRESCENT HILL,2762 FRANKFORT AVE,LOUISVILLE KY 40206,https://www.lfpl.org/crescent-hill-1,502-574-1793,38.254545,-85.691115
4,1.263650e+06,256800.36000,5,JEFFERSONTOWN,10635 WATTERSON TRL,LOUISVILLE KY 40299,https://www.lfpl.org/jeffersontown-0,502-267-5713,38.197827,-85.561087

In [13]:
lfpl_loc[['city', 'state', 'zipcode']] = lfpl_loc['LFPL_LOC'].str.split (' ', expand=True)

In [14]:
lfpl_loc = lfpl_loc.drop(['LFPL_LOC', 'LFPL_WEB', 'TELEPHONE', 'LFPL_ADD', 'city', 'state'], axis=1)

In [15]:
lfpl_loc.head()

,X,Y,OBJECTID,LFPL_NAME,LATITUDE,LONGITUDE,zipcode
0,1.236710e+06,263517.29000,1,BON AIR,38.215179,-85.655178,40220
1,1.205783e+06,224288.89875,2,FAIRDALE,38.106126,-85.760568,40118
2,1.203085e+06,252215.11875,3,IROQUOIS,38.182680,-85.771544,40215
3,1.226610e+06,278010.77000,4,CRESCENT HILL,38.254545,-85.691115,40206
4,1.263650e+06,256800.36000,5,JEFFERSONTOWN,38.197827,-85.561087,40299

In [16]:
lfpl_loc.rename(columns={'OBJECTID': 'library_id', 'LFPL_NAME': 'library_name', 'LATITUDE': 'latitude', 'LONGITUDE': 'longitude'}, inplace=True)

In [17]:
lfpl_loc.head()

,X,Y,library_id,library_name,latitude,longitude,zipcode
0,1.236710e+06,263517.29000,1,BON AIR,38.215179,-85.655178,40220
1,1.205783e+06,224288.89875,2,FAIRDALE,38.106126,-85.760568,40118
2,1.203085e+06,252215.11875,3,IROQUOIS,38.182680,-85.771544,40215
3,1.226610e+06,278010.77000,4,CRESCENT HILL,38.254545,-85.691115,40206
4,1.263650e+06,256800.36000,5,JEFFERSONTOWN,38.197827,-85.561087,40299