In [1]:
import pandas as pd

In [2]:
zips = pd.read_csv('../data/Raw/Jefferson_County_KY_ZIP_Codes.csv')

In [3]:
zips.head()

   OBJECTID  ZIPCODE     SHAPEAREA       SHAPELEN
0         1    40203  8.608996e+07   76402.584655
1         2    40210  8.825244e+07   58504.651674
2         3    40059  3.342632e+08  102937.557822
3         4    40220  2.150630e+08   85234.904721
4         5    40041  3.513355e+06    8445.222310

In [4]:
zips = zips.drop('OBJECTID', axis=1)

In [5]:
zips.head()

   ZIPCODE     SHAPEAREA       SHAPELEN
0    40203  8.608996e+07   76402.584655
1    40210  8.825244e+07   58504.651674
2    40059  3.342632e+08  102937.557822
3    40220  2.150630e+08   85234.904721
4    40041  3.513355e+06    8445.222310

In [6]:
zips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ZIPCODE    42 non-null     int64
 1   SHAPEAREA  42 non-null     float64
 2   SHAPELEN   42 non-null     float64
dtypes: float64(2), int64(1)
memory usage: 1.1 KB

In [7]:
zips['ZIPCODE'] = zips['ZIPCODE'].astype(object)

In [8]:
zips = zips.drop(['SHAPEAREA', 'SHAPELEN'], axis=1)

In [9]:
zips = zips.rename(columns={'ZIPCODE':'zipcode'})

In [10]:
zips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   zipcode  42 non-null     object
dtypes: object(1)
memory usage: 468.0+ bytes

In [11]:
zips = zips.drop_duplicates(subset=['zipcode'])

In [12]:
zips.to_csv('../data/Clean/clean_zips.csv', index=False)